# Generated by Django 5.2.17 on 2026-09-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('day', models.CharField(choices=[('Day 1', 'Day 1 (Fri)'), ('Day 2', 'Day 2 (Sat)'), ('Day 3', 'Day 3 (Sun)')], default='Day 1', max_length=10)),
                ('time_slot', models.CharField(help_text='e.g. 19:00 - 21:00', max_length=60)),
                ('location', models.CharField(help_text='Stage or venue name', max_length=120)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Food', 'Food'), ('Show', 'Show'), ('Workshop', 'Workshop'), ('Sports', 'Sports'), ('Other', 'Other')], default='Music', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('image_url', models.URLField(blank=True, help_text='Used when no image file is uploaded')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day', 'time_slot', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('category', models.CharField(choices=[('Sound & Stage', 'Sound & Stage Quality'), ('Food & Drinks', 'Food & Drinks Vendors'), ('Facilities & Cleanliness', 'Facilities & Cleanliness'), ('Security & Safety', 'Security & Safety'), ('General Suggestion', 'General Suggestion')], default='General Suggestion', max_length=40)),
                ('comment', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('festival_day', models.CharField(blank=True, max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Stage', 'Main Stage'), ('Crowd', 'Crowd Vibes'), ('Night', 'Night Lights')], default='Stage', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('author', models.CharField(default='Festival Fan', max_length=80)),
                ('is_approved', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='festival.poll')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='festival.event')),
            ],
            options={
                'unique_together': {('event', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_likes', to='festival.photo')),
            ],
            options={
                'unique_together': {('photo', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='festival.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='festival.poll')),
            ],
            options={
                'unique_together': {('poll', 'session_key')},
            },
        ),
    ]
