# Generated by Django 5.2.17 on 2026-09-15 09:10

import festival.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=festival.models.festival_day_choices, default='Day 1', max_length=10),
        ),
    ]
