# Generated by Django 5.2.17 on 2026-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_alter_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Ritual', 'Ritual / Aarti'), ('Music', 'Music'), ('Show', 'Show'), ('Workshop', 'Workshop'), ('Food', 'Food'), ('Sports', 'Sports'), ('Other', 'Other')], default='Music', max_length=40),
        ),
    ]
