# Generated by Django 5.2.17 on 2026-09-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Dance', 'Dance'), ('Singing', 'Singing'), ('Sloka', 'Sloka Recitation'), ('Music', 'Instrumental Music'), ('Art', 'Art & Display'), ('Ritual', 'Ritual / Aarti'), ('Show', 'Show'), ('Workshop', 'Workshop'), ('Food', 'Food'), ('Sports', 'Sports'), ('Other', 'Other')], default='Music', max_length=40),
        ),
    ]
