# Generated by Django 5.2.17 on 2026-09-15 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='video',
            field=models.FileField(blank=True, help_text='Short clip: mp4 or webm play everywhere', null=True, upload_to='gallery/clips/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])]),
        ),
    ]
