# Generated by Django 5.2.17 on 2026-09-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_photo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TshirtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='Flat or villa number', max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('size', models.CharField(choices=[('Kids-S', 'Kids S (2-4 yrs)'), ('Kids-M', 'Kids M (5-7 yrs)'), ('Kids-L', 'Kids L (8-10 yrs)'), ('Kids-XL', 'Kids XL (11-13 yrs)'), ('XS', 'Adult XS'), ('S', 'Adult S'), ('M', 'Adult M'), ('L', 'Adult L'), ('XL', 'Adult XL'), ('XXL', 'Adult XXL'), ('XXXL', 'Adult XXXL')], max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_collected', models.BooleanField(default=False, help_text='Handed over and paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['flat_number', 'size'],
            },
        ),
    ]
