# Generated by Django 5.2.17 on 2026-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_tshirtorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtorder',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tshirtorder',
            name='size',
            field=models.CharField(choices=[('24', 'Size 24'), ('26', 'Size 26'), ('28', 'Size 28'), ('30', 'Size 30'), ('32', 'Size 32'), ('34', 'Size 34'), ('36', 'Size 36'), ('38', 'Size 38'), ('40', 'Size 40'), ('42', 'Size 42'), ('44', 'Size 44'), ('46', 'Size 46'), ('48', 'Size 48'), ('50', 'Size 50')], max_length=10),
        ),
    ]
